//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCupWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTAIN:.
        /// </summary>
        public static string Captain {
            get {
                return ResourceManager.GetString("Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string captainNo {
            get {
                return ResourceManager.GetString("captainNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string captainYes {
            get {
                return ResourceManager.GetString("captainYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Gender.
        /// </summary>
        public static string ChooseGender {
            get {
                return ResourceManager.GetString("ChooseGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string CloseAppConfContent {
            get {
                return ResourceManager.GetString("CloseAppConfContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the application.
        /// </summary>
        public static string ConfirmSettings {
            get {
                return ResourceManager.GetString("ConfirmSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFEATS:.
        /// </summary>
        public static string Defeats {
            get {
                return ResourceManager.GetString("Defeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        public static string Defender {
            get {
                return ResourceManager.GetString("Defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRAWS:.
        /// </summary>
        public static string Draws {
            get {
                return ResourceManager.GetString("Draws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while fetching data.
        /// </summary>
        public static string ErrorDataFetch {
            get {
                return ResourceManager.GetString("ErrorDataFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite team:.
        /// </summary>
        public static string FavouriteTeam {
            get {
                return ResourceManager.GetString("FavouriteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap field {
            get {
                object obj = ResourceManager.GetObject("field", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA CODE:.
        /// </summary>
        public static string FifaCode {
            get {
                return ResourceManager.GetString("FifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string Fullscreen {
            get {
                return ResourceManager.GetString("Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMES PLAYED:.
        /// </summary>
        public static string GamesPlayed {
            get {
                return ResourceManager.GetString("GamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOAL DIFFERENCE:.
        /// </summary>
        public static string GoalDiff {
            get {
                return ResourceManager.GetString("GoalDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goalie.
        /// </summary>
        public static string Goalie {
            get {
                return ResourceManager.GetString("Goalie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOALS:.
        /// </summary>
        public static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOALS AGAINST:.
        /// </summary>
        public static string GoalsAgainst {
            get {
                return ResourceManager.GetString("GoalsAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOALS FOR:.
        /// </summary>
        public static string GoalsFor {
            get {
                return ResourceManager.GetString("GoalsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial settings.
        /// </summary>
        public static string InitialSettings {
            get {
                return ResourceManager.GetString("InitialSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string langCro {
            get {
                return ResourceManager.GetString("langCro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string langEn {
            get {
                return ResourceManager.GetString("langEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading content....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midfield.
        /// </summary>
        public static string Midfield {
            get {
                return ResourceManager.GetString("Midfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country statistics.
        /// </summary>
        public static string NationStat {
            get {
                return ResourceManager.GetString("NationStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        public static string Opponet {
            get {
                return ResourceManager.GetString("Opponet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player statistics.
        /// </summary>
        public static string PlayerStat {
            get {
                return ResourceManager.GetString("PlayerStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSITION:.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string ResLarge {
            get {
                return ResourceManager.GetString("ResLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string ResMedium {
            get {
                return ResourceManager.GetString("ResMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string ResSmall {
            get {
                return ResourceManager.GetString("ResSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIRT NUMBER:.
        /// </summary>
        public static string ShirtNumber {
            get {
                return ResourceManager.GetString("ShirtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show main window.
        /// </summary>
        public static string ShowMain {
            get {
                return ResourceManager.GetString("ShowMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string TeamDisplay {
            get {
                return ResourceManager.GetString("TeamDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINS:.
        /// </summary>
        public static string Wins {
            get {
                return ResourceManager.GetString("Wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YELLOW CARDS:.
        /// </summary>
        public static string YellowCard {
            get {
                return ResourceManager.GetString("YellowCard", resourceCulture);
            }
        }
    }
}
