//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupWF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCupWF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away Team.
        /// </summary>
        internal static string Away_Team {
            get {
                return ResourceManager.GetString("Away Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_profile_picture {
            get {
                object obj = ResourceManager.GetObject("blank-profile-picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        internal static string Captain {
            get {
                return ResourceManager.GetString("Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Options.
        /// </summary>
        internal static string Confirm_Options {
            get {
                return ResourceManager.GetString("Confirm Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cup Gender.
        /// </summary>
        internal static string Cup_Gender {
            get {
                return ResourceManager.GetString("Cup Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close app?.
        /// </summary>
        internal static string Do_you_want_to_close_app {
            get {
                return ResourceManager.GetString("Do you want to close app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Players.
        /// </summary>
        internal static string Favourite_Players {
            get {
                return ResourceManager.GetString("Favourite Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Team.
        /// </summary>
        internal static string Favourite_Team {
            get {
                return ResourceManager.GetString("Favourite Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        internal static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Team.
        /// </summary>
        internal static string Home_Team {
            get {
                return ResourceManager.GetString("Home Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Image.
        /// </summary>
        internal static string Load_Image {
            get {
                return ResourceManager.GetString("Load Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches Played.
        /// </summary>
        internal static string Matches_Played {
            get {
                return ResourceManager.GetString("Matches Played", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches Rang List.
        /// </summary>
        internal static string Matches_Rang_List {
            get {
                return ResourceManager.GetString("Matches Rang List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Fav.
        /// </summary>
        internal static string Move_To_Fav {
            get {
                return ResourceManager.GetString("Move To Fav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        internal static string Player_Name {
            get {
                return ResourceManager.GetString("Player Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Pictures.
        /// </summary>
        internal static string Player_Pictures {
            get {
                return ResourceManager.GetString("Player Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players Rang List.
        /// </summary>
        internal static string Players_Rang_List {
            get {
                return ResourceManager.GetString("Players Rang List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Details.
        /// </summary>
        internal static string Print_Details {
            get {
                return ResourceManager.GetString("Print Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Fav.
        /// </summary>
        internal static string Remove_from_Fav {
            get {
                return ResourceManager.GetString("Remove from Fav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation Saved.
        /// </summary>
        internal static string Saved_Nation {
            get {
                return ResourceManager.GetString("Saved Nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Player.
        /// </summary>
        internal static string Select_Player {
            get {
                return ResourceManager.GetString("Select Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Your Favourite Team From Dropdown.
        /// </summary>
        internal static string Select_Your_Favourite_Team_From_Dropdown {
            get {
                return ResourceManager.GetString("Select Your Favourite Team From Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        internal static string Visitors {
            get {
                return ResourceManager.GetString("Visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Cards.
        /// </summary>
        internal static string Yellow_Cards {
            get {
                return ResourceManager.GetString("Yellow Cards", resourceCulture);
            }
        }
    }
}
